/* GENERATED FILE — do not edit.
   Built from packs/*.csv by scripts/build-activities.mjs. Change an activity
   by changing the CSV and running that, then commit both. */
export const PACKS = [
  { id:"core", name:"The core deck", note:"Everything the app shipped with.", on:true, items:[
    {id:'a77u1d',t:"Write the first page of the thing you keep meaning to write",tags:["create","writing","challenging","anywhere","medium","free"],min:45,cost:0},
    {id:'a5qlvxc',t:"Write a letter by hand and actually post it",tags:["create","writing","kindness","casual","home","medium","free"],min:40,cost:0},
    {id:'a1muj0v5',t:"Write down everything you remember about one particular day",tags:["create","writing","nostalgic","engaging","anywhere","medium","free"],min:40,cost:0},
    {id:'ajw7vup',t:"Sit in a café and describe a stranger in two hundred words",tags:["create","writing","engaging","indoors","medium","frugal"],min:35,cost:1},
    {id:'a1ch1i5l',t:"Keep a one-line diary for the rest of the week",tags:["create","writing","mindful","casual","anywhere","short","free"],min:10,cost:0},
    {id:'a64gdfe',t:"Write a completely serious review of a sandwich",tags:["create","writing","funny","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'a1w873wi',t:"Write a poem in a form you have never used",tags:["create","writing","try","challenging","anywhere","medium","free"],min:50,cost:0},
    {id:'a13tikla',t:"Write the best possible argument for the thing you disagree with",tags:["create","writing","challenging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1ii3j14',t:"Write a scene that is nothing but dialogue",tags:["create","writing","engaging","anywhere","medium","free"],min:40,cost:0},
    {id:'a1e0acqc',t:"Write down the story your family always tells",tags:["create","writing","nostalgic","engaging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1ylucd9',t:"Write a letter to yourself to open in a year",tags:["create","writing","mindful","casual","home","medium","free"],min:30,cost:0},
    {id:'acfu12e',t:"Invent a word and use it all week",tags:["create","writing","funny","casual","anywhere","short","free"],min:15,cost:0},
    {id:'af16j49',t:"Write six-word stories until one of them lands",tags:["create","writing","funny","casual","anywhere","short","free"],min:25,cost:0},
    {id:'a1enzhta',t:"Write the opening of a horror story set in your own house",tags:["create","writing","spooky","engaging","home","medium","free"],min:40,cost:0},
    {id:'ags4p76',t:"Keep a notebook in your pocket all day and fill it",tags:["create","writing","engaging","anywhere","medium","free"],min:60,cost:0},
    {id:'a1d4qihu',t:"Write instructions for something you do without thinking",tags:["create","writing","funny","engaging","home","medium","free"],min:35,cost:0},
    {id:'a1gjr0c7',t:"Draw the room you are in, badly",tags:["create","visualart","drawing","casual","mindful","home","short","free"],min:25,cost:0},
    {id:'ac5rp38',t:"Redraw a logo you see every day, from memory",tags:["create","visualart","drawing","funny","casual","home","short","free"],min:25,cost:0},
    {id:'a1trvk84',t:"Draw the same object ten times",tags:["create","visualart","drawing","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1i7pzd1',t:"Draw somebody without once looking at the paper",tags:["create","visualart","drawing","funny","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a12e84r1',t:"Fill one whole page with nothing but circles",tags:["create","visualart","drawing","mindful","casual","home","short","free"],min:25,cost:0},
    {id:'a1jnvt26',t:"Draw your street from memory, then walk it and check",tags:["create","visualart","drawing","engaging","anywhere","medium","free"],min:60,cost:0},
    {id:'a1k6axou',t:"Draw with your other hand for half an hour",tags:["create","visualart","drawing","funny","casual","home","medium","free"],min:30,cost:0},
    {id:'a1inv3ch',t:"Draw a map of somewhere you have never been",tags:["create","visualart","drawing","engaging","adventurous","home","medium","free"],min:45,cost:0},
    {id:'a7o3ixs',t:"Sit somewhere public and sketch whatever is in front of you",tags:["create","visualart","drawing","engaging","indoors","medium","free"],min:45,cost:0},
    {id:'agcq04j',t:"Draw a comic strip about your own week",tags:["create","visualart","drawing","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'apj5cqt',t:"Copy a drawing by somebody far better than you",tags:["create","visualart","drawing","learn","engaging","home","medium","free"],min:60,cost:0},
    {id:'a14n3d68',t:"Draw the floor plan of every home you have lived in",tags:["create","visualart","drawing","nostalgic","engaging","home","medium","free"],min:50,cost:0},
    {id:'aiqxoob',t:"Paint something you are not allowed to be good at",tags:["create","visualart","painting","casual","home","medium","frugal"],min:40,cost:1},
    {id:'a17x09e6',t:"Paint the view out of one window",tags:["create","visualart","painting","engaging","home","medium","frugal"],min:75,cost:1},
    {id:'a1psl3lu',t:"Mix one colour until it is exactly right",tags:["create","visualart","painting","mindful","engaging","home","medium","frugal"],min:40,cost:1},
    {id:'a1cub611',t:"Paint something using one colour and white",tags:["create","visualart","painting","challenging","try","home","medium","frugal"],min:60,cost:1},
    {id:'a1arjceh',t:"Paint over something you had already finished",tags:["create","visualart","painting","try","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1bna0la',t:"Paint a portrait from a photograph on your phone",tags:["create","visualart","painting","challenging","home","medium","frugal"],min:90,cost:1},
    {id:'a1fc2re0',t:"Buy the cheapest canvas there is and ruin it on purpose",tags:["create","visualart","painting","funny","casual","home","medium","frugal"],min:40,cost:1},
    {id:'a1je80q2',t:"Paint something the size of a postcard and post it to somebody",tags:["create","visualart","painting","kindness","casual","home","medium","frugal"],min:45,cost:1},
    {id:'acqrwge',t:"Cast your own hand in plaster",tags:["create","visualart","sculpting","engaging","home","medium","frugal"],min:90,cost:1},
    {id:'a1xaflh0',t:"Make something out of what is in the recycling",tags:["create","visualart","mixedmedia","funny","casual","home","medium","free"],min:60,cost:0},
    {id:'adsqxif',t:"Carve a stamp out of an eraser and print with it",tags:["create","visualart","mixedmedia","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1giybqs',t:"Make a collage out of one magazine",tags:["create","visualart","mixedmedia","casual","home","medium","frugal"],min:45,cost:1},
    {id:'a1f1ampf',t:"Model something out of clay with your eyes shut",tags:["create","visualart","sculpting","funny","try","casual","home","medium","frugal"],min:40,cost:1},
    {id:'a1vmkmoy',t:"Make a zine — eight pages out of one sheet of paper",tags:["create","visualart","mixedmedia","writing","engaging","home","medium","free"],min:90,cost:0},
    {id:'andvb7y',t:"Bind your own notebook",tags:["create","visualart","mixedmedia","learn","engaging","home","medium","frugal"],min:75,cost:1},
    {id:'anzfq7y',t:"Mend a garment so that the mend shows",tags:["create","clothes","repair","mindful","engaging","home","medium","free"],min:45,cost:0},
    {id:'aabd15o',t:"Dye something you had got bored of",tags:["create","clothes","try","engaging","home","medium","frugal"],min:90,cost:1},
    {id:'afzi2vt',t:"Take a jacket in until it actually fits you",tags:["create","clothes","repair","challenging","home","medium","frugal"],min:120,cost:1},
    {id:'a13w3az2',t:"Make one thing you would otherwise have bought",tags:["create","visualart","mixedmedia","challenging","try","home","medium","frugal"],min:120,cost:1},
    {id:'abnpzzr',t:"Print photographs out and put them on a wall",tags:["create","visualart","nostalgic","casual","anywhere","medium","frugal"],min:45,cost:1},
    {id:'an8ex7w',t:"Make a mask",tags:["create","visualart","sculpting","spooky","engaging","home","medium","frugal"],min:90,cost:1},
    {id:'aeta513',t:"Sew something with no pattern",tags:["create","clothes","challenging","try","home","medium","frugal"],min:120,cost:1},
    {id:'aiqfk8z',t:"Build a tiny shelf for the place that has needed one for months",tags:["create","repair","challenging","home","medium","frugal"],min:120,cost:1},
    {id:'a1wgkbah',t:"Learn one song all the way through, including the part you skip",tags:["create","music","learn","engaging","home","medium","free"],min:60,cost:0},
    {id:'a3kcrs5',t:"Make a playlist that tells a story",tags:["create","music","organize","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'a1oktos4',t:"Make a mixtape for one specific person",tags:["create","music","kindness","nostalgic","engaging","home","medium","free"],min:60,cost:0},
    {id:'azmsbvh',t:"Record the sound of somewhere and keep it",tags:["create","music","listen","casual","outdoors","short","free"],min:20,cost:0},
    {id:'a1apz9j3',t:"Write a song about something extremely boring",tags:["create","music","writing","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'a1qhn6pi',t:"Sing somewhere with very good reverb",tags:["create","music","funny","casual","anywhere","quick","free"],min:3,cost:0},
    {id:'a18fmhh7',t:"Learn the first four bars on an instrument you cannot play",tags:["create","music","try","challenging","home","medium","free"],min:45,cost:0},
    {id:'a1q1edho',t:"Work out a song by ear, with no tabs",tags:["create","music","challenging","learn","home","medium","free"],min:60,cost:0},
    {id:'anh5glm',t:"Play music with somebody else in the room",tags:["create","music","friends","engaging","anywhere","medium","free"],min:90,cost:0},
    {id:'awcor8g',t:"Make a beat out of household objects",tags:["create","music","funny","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1nlap4d',t:"Sing the harmony instead of the tune",tags:["create","music","try","engaging","anywhere","short","free"],min:25,cost:0},
    {id:'a1c9rbk3',t:"Busk once, badly, for nobody",tags:["create","music","challenging","adventurous","indoors","newpeople","friends","medium","free"],min:60,cost:0},
    {id:'a148pc0t',t:"Write down every song you loved at fifteen",tags:["create","music","nostalgic","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'ajxb62o',t:"Learn a song in a language you do not speak",tags:["create","music","try","engaging","home","medium","free"],min:60,cost:0},
    {id:'asmty5y',t:"Read a play out loud, all the parts, on your own",tags:["create","acting","funny","engaging","home","medium","free"],min:90,cost:0},
    {id:'a51n1tt',t:"Learn a monologue and perform it to a mirror",tags:["create","acting","challenging","home","medium","free"],min:60,cost:0},
    {id:'a18p0ej1',t:"Do a scene with somebody, both of you terrible",tags:["create","acting","friends","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'a1km5jb8',t:"Record yourself telling a story and watch it back",tags:["create","acting","challenging","home","medium","free"],min:40,cost:0},
    {id:'a12lvytj',t:"Learn to do one convincing accent",tags:["create","acting","try","engaging","home","medium","free"],min:45,cost:0},
    {id:'aspjnb0',t:"Improvise a scene with one rule neither of you can break",tags:["create","acting","friends","funny","engaging","home","medium","free"],min:45,cost:0},
    {id:'al34ltz',t:"Read a picture book out loud with full commitment",tags:["create","acting","funny","casual","home","quick","free"],min:4,cost:0},
    {id:'a1mb6cx4',t:"Dance to three songs with the door shut",tags:["create","dancing","funny","move","casual","home","short","free"],min:15,cost:0},
    {id:'awyscwx',t:"Learn one dance properly from a video",tags:["create","dancing","learn","move","engaging","home","medium","free"],min:60,cost:0},
    {id:'aaq9wcu',t:"Go dancing somewhere you would normally leave early",tags:["create","dancing","friends","move","adventurous","engaging","indoors","newpeople","long","frugal"],min:180,cost:1},
    {id:'avfpmg7',t:"Dance in the kitchen while the dinner cooks",tags:["create","dancing","romantic","funny","casual","home","partner","short","free"],min:10,cost:0},
    {id:'a4vqgly',t:"Learn the steps to something out of a film",tags:["create","dancing","nostalgic","learn","engaging","home","medium","free"],min:60,cost:0},
    {id:'ay023a0',t:"Move for one whole song with your eyes closed",tags:["create","dancing","mindful","move","casual","home","short","free"],min:10,cost:0},
    {id:'a1nrtx5n',t:"Slow dance to one song in the kitchen",tags:["create","dancing","romantic","music","casual","home","partner","short","free"],min:10,cost:0},
    {id:'avkabgw',t:"Shoot a one-minute film on your phone with no cuts",tags:["create","film","challenging","anywhere","medium","free"],min:60,cost:0},
    {id:'a4c6lcc',t:"Film the same place at four different times of day",tags:["create","film","mindful","engaging","outdoors","medium","free"],min:90,cost:0},
    {id:'a1ptpq5b',t:"Make a title sequence for a film that does not exist",tags:["create","film","funny","engaging","home","medium","free"],min:90,cost:0},
    {id:'a76o99f',t:"Learn to edit one thing properly",tags:["create","film","learn","challenging","home","medium","free"],min:120,cost:0},
    {id:'a15iw9yq',t:"Film somebody you love doing the thing they always do",tags:["create","film","kindness","nostalgic","engaging","anywhere","medium","free"],min:45,cost:0},
    {id:'a33mc2a',t:"Remake a scene you know by heart, badly",tags:["create","film","acting","funny","friends","engaging","anywhere","medium","free"],min:120,cost:0},
    {id:'a1ctqucv',t:"Shoot a whole roll of film and wait a week for it",tags:["create","film","visualart","adventurous","engaging","outdoors","medium","frugal"],min:120,cost:1},
    {id:'a1i2nl9z',t:"Make a stop-motion ten seconds long",tags:["create","film","funny","challenging","home","medium","free"],min:120,cost:0},
    {id:'aoxgfz4',t:"Take a hundred photographs of one object",tags:["create","visualart","engaging","learn","home","medium","free"],min:45,cost:0},
    {id:'aomxta8',t:"Photograph ten things that are all the same colour",tags:["create","visualart","engaging","outdoors","medium","free"],min:60,cost:0},
    {id:'a1l1y76v',t:"Take photographs at night on a long exposure",tags:["create","visualart","film","spooky","engaging","outdoors","medium","free"],min:90,cost:0},
    {id:'az49cbr',t:"Clear one surface completely and then stop",tags:["organize","clean","mindful","casual","home","medium","free"],min:30,cost:0},
    {id:'a1agabc8',t:"Rearrange one room properly",tags:["organize","move","challenging","home","long","free"],min:150,cost:0},
    {id:'a1en7x1g',t:"Put every photograph from one year into an album",tags:["organize","nostalgic","engaging","anywhere","medium","free"],min:60,cost:0},
    {id:'a1vb1o66',t:"Deal with the drawer of paper",tags:["organize","challenging","home","medium","free"],min:60,cost:0},
    {id:'a12hq31o',t:"Work out one thing about your own money",tags:["organize","learn","engaging","home","medium","free"],min:40,cost:0},
    {id:'a1q3q6aj',t:"Write down ten things you would do with a free Saturday",tags:["organize","writing","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a1jtsns0',t:"Put your books in an order that means something",tags:["organize","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'apkkz05',t:"Cancel one subscription you had forgotten about",tags:["organize","casual","home","short","free"],min:15,cost:0},
    {id:'a3zqlqn',t:"Plan next week on paper rather than on a screen",tags:["organize","mindful","casual","home","medium","free"],min:30,cost:0},
    {id:'avn7y5q',t:"Give away five things today",tags:["organize","kindness","casual","home","medium","free"],min:45,cost:0},
    {id:'a3029oy',t:"Name every file on your desktop properly",tags:["organize","casual","home","medium","free"],min:40,cost:0},
    {id:'a14f3kkg',t:"Make a list of everybody you owe a message",tags:["organize","kindness","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a13n1tiz',t:"Sort your clothes into what you actually wear",tags:["organize","challenging","clothes","home","medium","free"],min:90,cost:0},
    {id:'a1ozc5yy',t:"Empty one box you have not opened since you moved",tags:["organize","nostalgic","engaging","home","medium","free"],min:60,cost:0},
    {id:'am47jxp',t:"Write down what you want this year to have in it",tags:["organize","writing","mindful","engaging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1e7ykfa',t:"Put every tool back where tools go",tags:["organize","repair","casual","home","medium","free"],min:40,cost:0},
    {id:'afzgma5',t:"Put your affairs in order for exactly one hour",tags:["organize","mindful","engaging","home","medium","free"],min:60,cost:0},
    {id:'a1teszly',t:"Clean the one thing you always look past",tags:["clean","casual","home","short","free"],min:25,cost:0},
    {id:'a1xnjik4',t:"Wash the windows and notice the difference all week",tags:["clean","engaging","home","medium","free"],min:60,cost:0},
    {id:'a91bogn',t:"Clean your keyboard properly",tags:["clean","casual","home","short","free"],min:20,cost:0},
    {id:'a1spkse',t:"Descale everything that can be descaled",tags:["clean","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1m144gd',t:"Take everything out of the fridge and start again",tags:["clean","engaging","home","medium","free"],min:60,cost:0},
    {id:'aq77txb',t:"Polish something until it looks new",tags:["clean","mindful","engaging","home","medium","free"],min:40,cost:0},
    {id:'a1iv86hp',t:"Clean your shoes",tags:["clean","mindful","casual","home","short","free"],min:25,cost:0},
    {id:'a1pm4y44',t:"Sweep outside your own front door",tags:["clean","kindness","casual","home","short","free"],min:20,cost:0},
    {id:'a1l7qvm4',t:"Do the washing up with the radio on and no hurry",tags:["clean","mindful","listen","casual","home","medium","free"],min:30,cost:0},
    {id:'a1u1vn76',t:"Clean out whatever you drive or ride",tags:["clean","engaging","home","medium","free"],min:60,cost:0},
    {id:'a1gv5ofg',t:"Fix the thing you have been stepping over",tags:["repair","casual","home","medium","free"],min:30,cost:0},
    {id:'ahfks53',t:"Find out what is actually wrong with it before buying another",tags:["repair","learn","engaging","home","medium","free"],min:45,cost:0},
    {id:'a1774w49',t:"Glue the broken thing back together and let the join show",tags:["repair","create","mindful","engaging","home","medium","free"],min:45,cost:0},
    {id:'a16di8qu',t:"Sharpen every knife in the house",tags:["repair","engaging","learn","home","medium","frugal"],min:40,cost:1},
    {id:'a18ke2l6',t:"Oil the hinge that has been squeaking for months",tags:["repair","casual","home","short","free"],min:5,cost:0},
    {id:'a19fdehk',t:"Replace a fuse, a washer or a battery yourself",tags:["repair","learn","casual","home","medium","frugal"],min:30,cost:1},
    {id:'a1w3yr18',t:"Take something broken apart just to see inside it",tags:["repair","try","challenging","home","medium","free"],min:60,cost:0},
    {id:'a1vdcqnq',t:"Patch the wall you have been ignoring",tags:["repair","engaging","home","medium","frugal"],min:60,cost:1},
    {id:'a1w8ou3p',t:"Restring, retune or re-fit something you own",tags:["repair","engaging","learn","home","medium","frugal"],min:45,cost:1},
    {id:'aploi6y',t:"Fix somebody else’s broken thing",tags:["repair","kindness","engaging","anywhere","medium","free"],min:60,cost:0},
    {id:'azrqor0',t:"Learn how the boiler, the fuse box or the lock actually works",tags:["repair","learn","engaging","home","medium","free"],min:40,cost:0},
    {id:'a141i30i',t:"Try a class you would be visibly bad at",tags:["try","learn","challenging","indoors","newpeople","friends","medium","costly"],min:90,cost:2},
    {id:'a84943o',t:"Learn twenty words of a language you will never speak",tags:["try","learn","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'a1aakqcr',t:"Teach yourself one knot",tags:["try","learn","casual","anywhere","short","free"],min:15,cost:0},
    {id:'a165kq4g',t:"Learn to do one pull-up",tags:["try","move","challenging","home","short","frugal"],min:20,cost:1},
    {id:'al109s',t:"Learn to fold one good paper thing",tags:["try","create","casual","mindful","home","medium","free"],min:30,cost:0},
    {id:'a1m6cvyr',t:"Learn to make one cocktail properly",tags:["try","eat","learn","engaging","home","medium","frugal"],min:40,cost:1},
    {id:'a1poaw5g',t:"Cook with one ingredient you have never used",tags:["try","eat","engaging","home","medium","frugal"],min:90,cost:1},
    {id:'ayd81sh',t:"Learn five trees on your own street",tags:["try","learn","casual","outdoors","medium","free"],min:40,cost:0},
    {id:'a1b78uho',t:"Learn to identify five birds by their sound",tags:["try","learn","mindful","engaging","outdoors","medium","free"],min:45,cost:0},
    {id:'a8n6sgg',t:"Try the food you decided you hated as a child",tags:["try","eat","funny","casual","anywhere","medium","frugal"],min:40,cost:1},
    {id:'afuo5uf',t:"Learn one card trick well enough to fool somebody",tags:["try","play","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'a124jrzb',t:"Learn to juggle three things",tags:["try","play","move","challenging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1j3lpfz',t:"Write with your other hand for a whole day",tags:["try","funny","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a5jz6lp',t:"Learn to whistle properly",tags:["try","funny","casual","anywhere","short","free"],min:20,cost:0},
    {id:'ar3akn1',t:"Find out where your water comes from, then go and look at it",tags:["try","learn","engaging","anywhere","medium","free"],min:90,cost:0},
    {id:'anii9ib',t:"Watch a film by somebody whose name you do not know",tags:["watch","try","engaging","home","medium","frugal"],min:120,cost:1},
    {id:'a1jftjjd',t:"Watch something in a language you do not speak",tags:["watch","try","engaging","home","medium","free"],min:110,cost:0},
    {id:'a1e645a8',t:"Go to a matinee on your own",tags:["watch","solo","casual","indoors","long","costly"],min:150,cost:2},
    {id:'a1wzg2gv',t:"Watch the film one of you loves and the other has never seen",tags:["watch","romantic","engaging","home","partner","long","free"],min:150,cost:0},
    {id:'a171uz6s',t:"Watch the sun come up",tags:["watch","mindful","engaging","outdoors","medium","free"],min:75,cost:0},
    {id:'a14rbpod',t:"Watch a horror film with all the lights off",tags:["watch","spooky","engaging","home","medium","free"],min:110,cost:0},
    {id:'a1davjzr',t:"Go to a gallery and look at one room only",tags:["watch","mindful","engaging","indoors","medium","frugal"],min:60,cost:1},
    {id:'ab2vmvs',t:"Watch a sport you do not understand until you work out the rules",tags:["watch","try","funny","engaging","anywhere","medium","free"],min:90,cost:0},
    {id:'alcl6jq',t:"Watch the film that terrified you as a child",tags:["watch","spooky","nostalgic","engaging","home","medium","free"],min:110,cost:0},
    {id:'a1qnwisu',t:"Sit somewhere busy and watch people for an hour",tags:["watch","mindful","casual","indoors","medium","free"],min:60,cost:0},
    {id:'a59h0tg',t:"Watch a documentary about something you would never choose",tags:["watch","try","engaging","home","medium","free"],min:90,cost:0},
    {id:'ah31lj3',t:"Go to a play, even a bad one",tags:["watch","acting","engaging","indoors","newpeople","friends","long","costly"],min:180,cost:2},
    {id:'adm00j2',t:"Watch the whole credits and look up one name",tags:["watch","funny","casual","home","quick","free"],min:4,cost:0},
    {id:'a4irnr0',t:"Watch a thunderstorm from somewhere dry",tags:["watch","mindful","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'ahst05n',t:"Listen to an album in the dark, start to finish",tags:["listen","music","mindful","engaging","home","medium","free"],min:45,cost:0},
    {id:'asrybgw',t:"Find out what your favourite band listened to",tags:["listen","music","learn","engaging","anywhere","medium","free"],min:60,cost:0},
    {id:'a9hn9ar',t:"Go and see live music by somebody you have never heard of",tags:["listen","music","adventurous","engaging","indoors","newpeople","friends","long","costly"],min:180,cost:2},
    {id:'a198q1lw',t:"Learn the names of five instruments in a piece you love",tags:["listen","music","learn","engaging","anywhere","medium","free"],min:35,cost:0},
    {id:'a1xvldhp',t:"Listen to a whole radio station from another country",tags:["listen","try","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'ai3lkn0',t:"Sit outside and listen with your eyes closed for ten minutes",tags:["listen","mindful","casual","outdoors","short","free"],min:15,cost:0},
    {id:'az6ulpj',t:"Listen to the album that was everything when you were seventeen",tags:["listen","music","nostalgic","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'a6cki4b',t:"Ask somebody to play you their favourite song and say nothing",tags:["listen","music","friends","kindness","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a140uhdk',t:"Listen to a podcast about something you would never search for",tags:["listen","try","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'a1c8bnfj',t:"Put on music from the year you were born",tags:["listen","music","nostalgic","funny","casual","anywhere","medium","free"],min:40,cost:0},
    {id:'ak3xu8x',t:"Read the Wikipedia article you keep meaning to read",tags:["read","learn","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'ariw24y',t:"Reread the book that mattered when you were seventeen",tags:["read","nostalgic","engaging","home","long","free"],min:180,cost:0},
    {id:'a1fji6ue',t:"Read a whole magazine about something you know nothing about",tags:["read","try","casual","anywhere","medium","frugal"],min:60,cost:1},
    {id:'a14n350w',t:"Read a short story out loud to somebody",tags:["read","friends","kindness","engaging","home","medium","free"],min:45,cost:0},
    {id:'a7bkw2r',t:"Read the same short story as somebody else and argue about it",tags:["read","romantic","friends","engaging","home","partner","medium","free"],min:90,cost:0},
    {id:'a18wqt4r',t:"Read a ghost story in bed with one lamp on",tags:["read","spooky","casual","home","medium","free"],min:45,cost:0},
    {id:'ao1ngwb',t:"Go to a library with no idea what you want",tags:["read","adventurous","casual","indoors","medium","free"],min:60,cost:0},
    {id:'a1qyooau',t:"Read the first chapter of five books and keep one",tags:["read","casual","anywhere","medium","frugal"],min:60,cost:1},
    {id:'aqo50rj',t:"Read a poem a day until the week is out",tags:["read","mindful","casual","anywhere","short","free"],min:10,cost:0},
    {id:'akxfnez',t:"Read something written more than two hundred years ago",tags:["read","challenging","try","anywhere","medium","free"],min:60,cost:0},
    {id:'a1cinci4',t:"Read the local history of your own street",tags:["read","learn","nostalgic","engaging","anywhere","medium","free"],min:90,cost:0},
    {id:'a1tw4exx',t:"Read a whole book in one sitting",tags:["read","challenging","home","long","free"],min:300,cost:0},
    {id:'az40y71',t:"Walk to the furthest point you can reach in thirty minutes",tags:["travel","move","casual","outdoors","medium","free"],min:60,cost:0},
    {id:'a16oq3yb',t:"Take the first bus that arrives and ride it to the end",tags:["travel","adventurous","funny","engaging","indoors","long","frugal"],min:180,cost:1},
    {id:'axu6w5r',t:"Get off two stops early and walk the rest",tags:["travel","move","casual","outdoors","medium","free"],min:45,cost:0},
    {id:'a1x9i3hz',t:"Take a train one stop past where you usually get off",tags:["travel","romantic","adventurous","engaging","indoors","partner","long","frugal"],min:240,cost:1},
    {id:'a14agson',t:"Go somewhere by train with no bag and come back at night",tags:["travel","adventurous","engaging","indoors","allday","costly"],min:480,cost:2},
    {id:'a1c5g04t',t:"Climb the highest thing nearby and look at where you live",tags:["travel","move","engaging","outdoors","medium","free"],min:90,cost:0},
    {id:'au7jhs9',t:"Find water and follow it downstream until it gets boring",tags:["travel","move","engaging","outdoors","medium","free"],min:120,cost:0},
    {id:'a1ep9byn',t:"Walk one long road from end to end",tags:["travel","move","challenging","outdoors","long","free"],min:180,cost:0},
    {id:'a1hoh6hd',t:"Go to the place tourists come to and be a tourist",tags:["travel","funny","casual","indoors","medium","frugal"],min:120,cost:1},
    {id:'a1nf1wc7',t:"Sleep outside",tags:["travel","adventurous","challenging","outdoors","allday","frugal"],min:600,cost:1},
    {id:'a19076a3',t:"Walk a route you know well, at night",tags:["travel","mindful","casual","outdoors","medium","free"],min:45,cost:0},
    {id:'afb4rfa',t:"Go somewhere with no map and no plan",tags:["travel","adventurous","engaging","outdoors","medium","free"],min:75,cost:0},
    {id:'aic73bq',t:"Find the oldest thing near you and go and stand next to it",tags:["travel","learn","nostalgic","casual","indoors","medium","free"],min:75,cost:0},
    {id:'a7nshi3',t:"Get up at five and go somewhere",tags:["travel","adventurous","engaging","outdoors","long","free"],min:180,cost:0},
    {id:'aseue04',t:"Cycle somewhere you would normally drive",tags:["travel","move","engaging","outdoors","medium","free"],min:75,cost:0},
    {id:'af35b9r',t:"Go and look at a building you have only ever seen photographs of",tags:["travel","learn","engaging","indoors","medium","frugal"],min:120,cost:1},
    {id:'a177r3mn',t:"Take a ferry for no reason",tags:["travel","adventurous","casual","outdoors","medium","frugal"],min:120,cost:1},
    {id:'a1ye44hx',t:"Go somewhere neither of you has ever been",tags:["travel","romantic","adventurous","engaging","outdoors","partner","long","frugal"],min:240,cost:1},
    {id:'as6kktm',t:"Cook something you have never cooked, properly",tags:["eat","create","engaging","home","medium","frugal"],min:120,cost:1},
    {id:'ake2npd',t:"Make bread from scratch",tags:["eat","create","engaging","home","long","free"],min:240,cost:0},
    {id:'a1gwlct5',t:"Eat at the place you always walk past",tags:["eat","casual","indoors","newpeople","friends","medium","frugal"],min:90,cost:1},
    {id:'az0dosl',t:"Make a proper breakfast on a weekday",tags:["eat","mindful","kindness","casual","home","medium","free"],min:45,cost:0},
    {id:'awlqlhf',t:"Bake something and give it away",tags:["eat","create","kindness","engaging","home","medium","frugal"],min:120,cost:1},
    {id:'a1f6po5p',t:"Have a picnic in unglamorous weather",tags:["eat","mindful","casual","outdoors","medium","frugal"],min:75,cost:1},
    {id:'a1egpfva',t:"Shop at a market instead of a supermarket",tags:["eat","casual","indoors","newpeople","friends","medium","frugal"],min:75,cost:1},
    {id:'a1aomwjh',t:"Cook the thing your family used to make",tags:["eat","create","nostalgic","kindness","engaging","home","medium","frugal"],min:120,cost:1},
    {id:'apa0by6',t:"Eat somewhere serving a cuisine you cannot name",tags:["eat","try","adventurous","casual","indoors","medium","frugal"],min:90,cost:1},
    {id:'a1d6m1ux',t:"Cook one dish together with no recipe between you",tags:["eat","romantic","create","friends","engaging","home","partner","medium","frugal"],min:120,cost:1},
    {id:'alfvi5h',t:"Go out for breakfast before work",tags:["eat","romantic","casual","indoors","partner","medium","frugal"],min:75,cost:1},
    {id:'a1vkv7h3',t:"Make the most complicated thing in the book",tags:["eat","challenging","create","home","long","costly"],min:300,cost:2},
    {id:'az6qfj2',t:"Eat by candlelight on an ordinary Tuesday",tags:["eat","romantic","mindful","casual","home","partner","medium","free"],min:60,cost:0},
    {id:'a1g870rn',t:"Cook for somebody who does not usually get cooked for",tags:["eat","kindness","friends","create","engaging","home","long","frugal"],min:150,cost:1},
    {id:'a1ig81d9',t:"Grow one thing you can eat",tags:["eat","create","engaging","home","medium","frugal"],min:60,cost:1},
    {id:'a67ymrs',t:"Pick something wild and eat it",tags:["eat","try","learn","engaging","outdoors","medium","free"],min:60,cost:0},
    {id:'agt3868',t:"Eat a meal with no phone anywhere in the room",tags:["eat","mindful","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'a7uo8s7',t:"Make something you have only ever bought",tags:["eat","create","try","engaging","home","medium","frugal"],min:90,cost:1},
    {id:'a1kv80c3',t:"Play a board game with actual people at an actual table",tags:["play","friends","funny","engaging","home","medium","frugal"],min:120,cost:1},
    {id:'a1cmkosl',t:"Go to a pub quiz and lose",tags:["play","friends","funny","engaging","indoors","newpeople","long","frugal"],min:150,cost:1},
    {id:'a175idii',t:"Play the game you loved as a child",tags:["play","nostalgic","funny","casual","home","medium","free"],min:60,cost:0},
    {id:'a1q23n1i',t:"Learn a card game nobody you know plays",tags:["play","try","learn","engaging","home","medium","free"],min:45,cost:0},
    {id:'avi8lgo',t:"Fly a kite badly",tags:["play","funny","move","casual","outdoors","medium","frugal"],min:60,cost:1},
    {id:'a1p6xv91',t:"Take up a sport you are too old to start",tags:["play","move","try","challenging","friends","indoors","newpeople","medium","frugal"],min:90,cost:1},
    {id:'a1jarfil',t:"Throw something at a wall and catch it a thousand times",tags:["play","move","mindful","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'a3yiux6',t:"Play hide and seek with somebody far too old for it",tags:["play","funny","friends","romantic","casual","home","medium","free"],min:30,cost:0},
    {id:'asvdz0i',t:"Set a puzzle going and leave it out all week",tags:["play","mindful","casual","home","medium","frugal"],min:30,cost:1},
    {id:'a1yy205m',t:"Skateboard, badly, in an empty car park",tags:["play","move","funny","adventurous","casual","outdoors","medium","frugal"],min:60,cost:1},
    {id:'a1m0ocb3',t:"Play chess against a stranger in a park",tags:["play","challenging","outdoors","newpeople","friends","medium","free"],min:60,cost:0},
    {id:'a133xym6',t:"Do a jigsaw and talk the whole way through it",tags:["play","romantic","mindful","friends","casual","home","partner","long","frugal"],min:150,cost:1},
    {id:'a1sucsg0',t:"Play twenty questions about something real",tags:["play","funny","friends","casual","anywhere","short","free"],min:20,cost:0},
    {id:'aja81pr',t:"Swim somewhere outdoors",tags:["play","move","adventurous","engaging","outdoors","medium","frugal"],min:90,cost:1},
    {id:'an1cmkf',t:"Invent a game out of the things on the table",tags:["play","funny","friends","create","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'a5ysmyi',t:"Play arcade games with actual coins",tags:["play","nostalgic","funny","friends","casual","indoors","medium","frugal"],min:60,cost:1},
    {id:'a1i5fis2',t:"Run the loop you always mean to run, slowly",tags:["move","engaging","outdoors","medium","free"],min:40,cost:0},
    {id:'a16d884b',t:"Walk ten thousand steps in one go",tags:["move","challenging","outdoors","medium","free"],min:120,cost:0},
    {id:'awh4b7z',t:"Swim lengths until you lose count",tags:["move","mindful","engaging","outdoors","medium","frugal"],min:60,cost:1},
    {id:'a1w66exe',t:"Carry something heavy up a hill",tags:["move","challenging","outdoors","medium","free"],min:45,cost:0},
    {id:'a1jmlmwy',t:"Do the exercise you are worst at",tags:["move","challenging","try","home","medium","free"],min:30,cost:0},
    {id:'a1uw3qn9',t:"Walk there and get the bus back",tags:["move","travel","casual","outdoors","medium","frugal"],min:90,cost:1},
    {id:'a1wm47ff',t:"Take the stairs everywhere for a day",tags:["move","casual","funny","anywhere","short","free"],min:20,cost:0},
    {id:'a1bwoynl',t:"Move every joint you own, once",tags:["move","mindful","casual","home","quick","free"],min:4,cost:0},
    {id:'a1nlsj0b',t:"Race somebody to the end of the road",tags:["move","funny","friends","casual","outdoors","short","free"],min:15,cost:0},
    {id:'a1fgjo97',t:"Stretch on the floor for twenty minutes",tags:["move","mindful","casual","home","short","free"],min:25,cost:0},
    {id:'a129x4p1',t:"Do nothing for twenty minutes on purpose",tags:["mindful","casual","home","short","free"],min:20,cost:0},
    {id:'a15q9hkr',t:"Have a bath with the phone in another room",tags:["mindful","casual","home","medium","free"],min:45,cost:0},
    {id:'aqfldjs',t:"Go to bed absurdly early",tags:["mindful","casual","home","medium","free"],min:30,cost:0},
    {id:'a1c7x58r',t:"Delete one app for a week",tags:["mindful","organize","casual","anywhere","short","free"],min:10,cost:0},
    {id:'a40orcp',t:"Walk with no destination and no podcast",tags:["mindful","move","casual","outdoors","medium","free"],min:45,cost:0},
    {id:'av9slp9',t:"Sit in one place outdoors for a whole hour",tags:["mindful","engaging","outdoors","medium","free"],min:60,cost:0},
    {id:'a1s2fh3s',t:"Watch the fire, or the rain, or the kettle",tags:["mindful","casual","anywhere","short","free"],min:15,cost:0},
    {id:'agd8i9h',t:"Say nothing for the first hour you are awake",tags:["mindful","challenging","home","medium","free"],min:60,cost:0},
    {id:'abrd886',t:"Plant something",tags:["mindful","create","casual","anywhere","medium","frugal"],min:60,cost:1},
    {id:'a1xbn0kg',t:"Lie on the floor and listen to one long piece of music",tags:["mindful","listen","music","casual","home","medium","free"],min:40,cost:0},
    {id:'ac8n1ix',t:"Look at the sky until you have found five things in it",tags:["mindful","casual","outdoors","quick","free"],min:4,cost:0},
    {id:'a1vpukx5',t:"Ring somebody instead of texting them",tags:["kindness","casual","anywhere","short","free"],min:25,cost:0},
    {id:'a159sx6k',t:"Have people over for something small",tags:["friends","kindness","eat","engaging","home","long","frugal"],min:180,cost:1},
    {id:'aawpu7l',t:"Organise the thing everybody says they want to do",tags:["friends","organize","kindness","challenging","anywhere","medium","free"],min:30,cost:0},
    {id:'a1dcqbwh',t:"Ask somebody to teach you what they are good at",tags:["friends","learn","kindness","engaging","anywhere","newpeople","medium","free"],min:90,cost:0},
    {id:'atot4f8',t:"Have one long conversation with no phones on the table",tags:["mindful","engaging","anywhere","medium","free"],min:120,cost:0},
    {id:'acq9ddc',t:"Walk beside somebody instead of sitting opposite them",tags:["friends","move","mindful","casual","outdoors","medium","free"],min:75,cost:0},
    {id:'a1vhs2yi',t:"Do the errand somebody else has been dreading",tags:["kindness","casual","anywhere","medium","free"],min:45,cost:0},
    {id:'a1xr5i0g',t:"Turn up to a local meeting about something",tags:["learn","kindness","engaging","indoors","newpeople","friends","medium","free"],min:90,cost:0},
    {id:'agjvxe6',t:"Volunteer for exactly one shift",tags:["kindness","challenging","indoors","newpeople","friends","long","free"],min:180,cost:0},
    {id:'a1f9kkqd',t:"Write to somebody who will never expect it",tags:["kindness","writing","nostalgic","casual","anywhere","medium","free"],min:30,cost:0},
    {id:'a9nx4w9',t:"Pick up litter along one street",tags:["kindness","move","casual","outdoors","medium","free"],min:30,cost:0},
    {id:'a1k7wb6l',t:"Leave something good for a stranger to find",tags:["kindness","funny","create","casual","indoors","short","free"],min:25,cost:0},
    {id:'a1m2i0k0',t:"Start the group chat that becomes a monthly thing",tags:["friends","organize","kindness","casual","anywhere","short","free"],min:20,cost:0},
    {id:'a16xbx3c',t:"Introduce two people who should already know each other",tags:["kindness","casual","anywhere","newpeople","friends","short","free"],min:20,cost:0},
    {id:'a1scfz2g',t:"Sit with somebody who is having a bad month",tags:["friends","kindness","mindful","engaging","anywhere","medium","free"],min:120,cost:0},
    {id:'a19szg7v',t:"Cook for your neighbours",tags:["kindness","eat","engaging","home","newpeople","friends","long","frugal"],min:150,cost:1},
    {id:'a1pjr8vu',t:"Interview each other about something you have never asked about",tags:["romantic","friends","mindful","engaging","anywhere","partner","medium","free"],min:60,cost:0},
    {id:'at6c3gf',t:"Get dressed up for no occasion at all",tags:["romantic","funny","casual","indoors","partner","long","costly"],min:180,cost:2},
    {id:'a5aawr5',t:"Plan a trip you might never take",tags:["romantic","organize","engaging","home","partner","medium","free"],min:90,cost:0},
    {id:'a1zayr7',t:"Walk home instead of getting a taxi",tags:["romantic","move","casual","outdoors","partner","medium","free"],min:60,cost:0},
    {id:'a1hdvj8w',t:"Write down five things you each want this year and compare",tags:["romantic","organize","writing","engaging","anywhere","partner","medium","free"],min:45,cost:0},
    {id:'a1ku5933',t:"Learn something together, badly",tags:["romantic","try","learn","funny","engaging","home","partner","medium","free"],min:45,cost:0},
    {id:'ay67z6u',t:"Reread the messages from when you first met",tags:["romantic","nostalgic","casual","anywhere","partner","medium","free"],min:30,cost:0},
    {id:'a13n4ts7',t:"Take a proper photograph of each other",tags:["romantic","create","visualart","engaging","anywhere","partner","medium","free"],min:45,cost:0},
    {id:'akhqil2',t:"Cook the meal from the night it started",tags:["romantic","eat","nostalgic","engaging","home","partner","medium","frugal"],min:120,cost:1},
    {id:'a8zjmub',t:"Give each other an hour with no interruptions",tags:["romantic","mindful","casual","home","partner","medium","free"],min:60,cost:0},
    {id:'a1qmn5y',t:"Go out on a weeknight as though it were a weekend",tags:["romantic","adventurous","casual","indoors","partner","long","frugal"],min:150,cost:1},
    {id:'a93wbek',t:"Watch the stars from somewhere with no streetlights",tags:["romantic","mindful","engaging","outdoors","partner","medium","free"],min:120,cost:0},
    {id:'a1uao0ql',t:"Argue properly about something that does not matter",tags:["romantic","funny","engaging","anywhere","partner","medium","free"],min:30,cost:0},
    {id:'abwhmxy',t:"Do the thing the other one always suggests",tags:["romantic","kindness","casual","anywhere","partner","medium","free"],min:90,cost:0},
    {id:'a4cxprw',t:"Walk a graveyard at dusk",tags:["spooky","mindful","casual","outdoors","medium","free"],min:45,cost:0},
    {id:'a1bo7ore',t:"Read about the strangest thing that ever happened where you live",tags:["spooky","read","learn","engaging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1fu43lh',t:"Tell ghost stories with the lights off",tags:["spooky","friends","funny","engaging","home","medium","free"],min:60,cost:0},
    {id:'apap56i',t:"Find the most abandoned-looking building near you and go and look",tags:["spooky","travel","adventurous","casual","indoors","medium","free"],min:60,cost:0},
    {id:'a1uxgp45',t:"Watch the horror film you have been avoiding",tags:["spooky","watch","challenging","home","medium","free"],min:110,cost:0},
    {id:'a9ej560',t:"Learn one genuinely unsettling fact and sit with it",tags:["spooky","learn","casual","anywhere","short","free"],min:20,cost:0},
    {id:'ar8pxyz',t:"Go somewhere very quiet at three in the morning",tags:["spooky","adventurous","challenging","outdoors","medium","free"],min:60,cost:0},
    {id:'aisk3ox',t:"Read a folk tale from wherever your family is from",tags:["spooky","read","nostalgic","learn","engaging","anywhere","medium","free"],min:45,cost:0},
    {id:'a1vwj8m2',t:"Make a playlist for a haunting",tags:["spooky","create","music","funny","casual","anywhere","medium","free"],min:40,cost:0},
    {id:'a1rxjj35',t:"Step outside and look up for two minutes",tags:["mindful","outdoors","casual","quick","free"],min:2,cost:0},
    {id:'aqlj9xv',t:"Send somebody a photograph of what you can see right now",tags:["kindness","anywhere","casual","quick","free"],min:2,cost:0},
    {id:'a1uf589x',t:"Write one sentence about today",tags:["create","writing","home","solo","casual","quick","free"],min:3,cost:0},
    {id:'a1accjid',t:"Learn one word in another language",tags:["learn","try","anywhere","solo","casual","quick","free"],min:3,cost:0},
    {id:'a15mjxqa',t:"Stand on one leg until you cannot",tags:["move","play","funny","anywhere","casual","quick","free"],min:2,cost:0},
    {id:'al3ky10',t:"Put on one song and do nothing else",tags:["listen","music","mindful","home","solo","casual","quick","free"],min:4,cost:0},
    {id:'a8f2nhg',t:"Look up what your street is named after",tags:["learn","read","anywhere","solo","casual","quick","free"],min:4,cost:0},
    {id:'a1i3slp3',t:"Water the plants",tags:["clean","mindful","home","solo","casual","quick","free"],min:4,cost:0},
    {id:'a8djrof',t:"Say the thing you have been meaning to say",tags:["kindness","anywhere","partner","friends","challenging","quick","free"],min:3,cost:0},
    {id:'aksy9mv',t:"Open a window and listen for one minute",tags:["listen","mindful","home","solo","casual","quick","free"],min:2,cost:0},
    {id:'a1kb8unw',t:"Draw one small thing in the corner of a page",tags:["create","drawing","visualart","home","solo","casual","quick","free"],min:4,cost:0},
    {id:'a1a7k3y9',t:"Take one photograph of something completely ordinary",tags:["create","visualart","anywhere","solo","casual","quick","free"],min:3,cost:0},
  ]},
  { id:"winter", name:"Winter", note:"An example pack — delete it or fill it in.", on:false, items:[
    {id:'akq6yua',t:"Walk somewhere in the snow before anybody else has",tags:["travel","move","outdoors","mindful","engaging","medium","free"],min:60,cost:0},
    {id:'avl1qcv',t:"Make a fire and sit in front of it doing nothing",tags:["mindful","indoors","engaging","medium","free"],min:90,cost:0},
    {id:'atku33c',t:"Cook something that takes all afternoon on purpose",tags:["eat","create","indoors","engaging","long","frugal"],min:240,cost:1},
    {id:'ae795j1',t:"Go out and look at other people's lit windows",tags:["travel","watch","outdoors","mindful","casual","medium","free"],min:40,cost:0},
    {id:'aksjvyj',t:"Learn to make one proper hot drink from scratch",tags:["try","eat","learn","indoors","engaging","medium","frugal"],min:45,cost:1},
    {id:'a1gftbjd',t:"Read a long book in one weekend",tags:["read","indoors","challenging","long","free"],min:300,cost:0},
    {id:'av6xg9s',t:"Write the year down before it gets away from you",tags:["create","writing","nostalgic","indoors","engaging","medium","free"],min:50,cost:0},
    {id:'axxwc9b',t:"Swim outdoors in cold water, once",tags:["play","move","outdoors","adventurous","challenging","medium","frugal"],min:45,cost:1},
    {id:'a1q52q4n',t:"Take the decorations down slowly and enjoy it",tags:["organize","clean","home","mindful","casual","medium","free"],min:60,cost:0},
    {id:'a1yj3lz6',t:"Plan the spring while it is still dark",tags:["organize","partner","indoors","engaging","medium","free"],min:60,cost:0},
    {id:'ah1v98e',t:"Watch the shortest day go by from start to finish",tags:["watch","mindful","outdoors","challenging","allday","free"],min:600,cost:0},
    {id:'a1astgmb',t:"Make something warm for somebody who is cold",tags:["create","clothes","kindness","indoors","engaging","medium","frugal"],min:120,cost:1},
  ]},
];
