/* Activinator — the deck's raw material.
   Seeds are hand-written activities. Twists are modifiers that turn a seed
   into a card you haven't seen before. Nothing here is generated by grammar:
   a twist is a second sentence, never a clause spliced into the title, because
   a splice eventually produces a sentence no person would say. */

/* Tag vocabulary. The key is what an activity stores; the label is what the
   taste screen prints. A tag is a feature the model learns a weight for, so
   adding one here is adding a dimension it can have an opinion about. */
const TAGS = {
  creative:'creative', making:'making things', hands:'hands-on', words:'writing',
  music:'music', watching:'watching', learning:'learning', food:'food',
  physical:'moving', outdoors:'outdoors', nature:'nature', water:'water',
  city:'the city', social:'people', talking:'talking', romance:'romance',
  kindness:'kindness', competitive:'competing', silly:'silly', calm:'calm',
  energetic:'high energy', ambitious:'ambitious', nostalgic:'nostalgia',
  screenfree:'screen-free', planning:'planning', night:'after dark',
  morning:'early', cheap:'free or nearly', splurge:'worth spending on',
  quick:'quick', longhaul:'a long one'
};

/* title | detail | tags | who | where | minutes | cost (0 free, 1 small, 2 real) */
const RAW = [
// — making, creative, solo —
['Draw the room you are in','Badly is fine. The point is looking at it for twenty minutes instead of glancing at it.','creative hands screenfree calm','any','home',25,0],
['Make something out of what is in the recycling','One object, no shopping, finished tonight.','making hands creative silly','any','home',60,0],
['Photograph ten things the same colour','Set out with one colour in your head and come back with ten frames of it.','creative outdoors city screenfree','any','out',60,0],
['Repair the thing you have been stepping over','The wobbly one. Glue, screwdriver, ten minutes of actually looking at it.','hands making quick','any','home',30,0],
['Build a tiny shelf','One board, two brackets, somewhere it has been needed for months.','making hands ambitious','any','home',120,1],
['Print photos and put them somewhere','Not the cloud. Paper, on a wall, where you will pass them.','creative nostalgic calm','any','any',45,1],
['Learn to fold one good paper thing','A crane, a box, a jumping frog. Do it until you can do it without the diagram.','hands learning calm quick','any','home',30,0],
['Redraw a logo you see every day','From memory first, then from life. The gap is the interesting part.','creative silly quick','any','home',25,0],
['Make a zine, eight pages, one sheet','Fold, cut, fill it with anything. Photocopy it and leave copies somewhere.','creative words making silly','any','home',90,0],
['Cast something in plaster','A hand, a leaf, a shape. Messy, cheap, weirdly satisfying.','making hands creative','any','home',90,1],
['Rearrange one room properly','Everything out, floor swept, back in a different order.','hands physical ambitious','any','home',150,0],
['Paint something you are not allowed to be good at','A cheap canvas, forty minutes, no editing.','creative hands calm','any','home',40,1],
['Make a stamp out of an eraser','Carve it, ink it, print it on every envelope for a year.','making hands creative','any','home',45,0],
['Fix a garment instead of replacing it','Visible mending counts and looks better anyway.','hands making calm','any','home',45,0],
['Build the thing you keep sketching','You know the one. Cardboard prototype tonight, decide tomorrow.','making ambitious hands creative','any','home',120,1],
['Bind a small notebook','Paper, thread, needle. There are twenty minutes of instructions and a lifetime of use.','making hands learning','any','home',75,1],
['Make a mixtape for one specific person','Order matters. Write why on the back.','music creative kindness nostalgic','any','home',60,0],
['Take a hundred photographs of one object','Move the light. Move yourself. Ninety of them will be bad.','creative learning screenfree','any','home',45,0],

// — words —
['Write the first page of the thing','Not the outline. The first page, badly, tonight.','words creative ambitious','any','any',45,0],
['Write a letter and post it','On paper, in an envelope, with a stamp, to somebody who will be startled.','words kindness nostalgic','any','home',40,0],
['Write down everything you remember about one day','Pick a date that mattered. See how much is still in there.','words nostalgic calm screenfree','any','any',40,0],
['Describe a stranger in two hundred words','From a café window. Nobody ever reads it. You get better at noticing.','words creative city','any','out',35,0],
['Keep a one-line diary for the rest of the week','One sentence a day. The bar has to be low enough to clear when tired.','words calm quick planning','any','any',10,0],
['Write the review nobody asked for','Of a sandwich, a bus route, a chair. Take it completely seriously.','words silly creative quick','any','any',30,0],
['Write down ten things you would do with a free Saturday','Then look at the list and notice which ones you could do this Saturday.','words planning quick','any','any',20,0],
['Write a poem in a form you do not know','Look up a villanelle or a ghazal and obey the rules for once.','words learning creative','any','any',50,0],

// — music and sound —
['Learn one song properly, start to finish','Not the intro. The whole thing, including the part you always skip.','music learning hands','any','home',60,0],
['Listen to an album with the lights off','No phone, no second screen. The whole thing in order, once.','music calm screenfree night','any','home',45,0],
['Record a voice memo of somewhere','Rain, a market, your street at 6am. Keep a folder of them.','music creative outdoors quick','any','out',20,0],
['Find out what your favourite band listened to','Follow it two steps back and listen to what you find.','music learning nostalgic','any','any',60,0],
['Sing somewhere with good reverb','A stairwell, a car park, a tiled bathroom. Nobody has to hear it.','music silly energetic quick','any','any',15,0],
['Make a playlist that tells a story','Beginning, middle, end. Give it a title that gives nothing away.','music creative planning','any','any',45,0],
['Go and see live music you know nothing about','Cheapest ticket, unfamiliar name, no research first.','music social night city splurge','any','out',180,2],
['Learn the names of five instruments in a piece you love','Then listen again and pick them out one at a time.','music learning calm','any','any',35,0],

// — outdoors and nature —
['Walk to the furthest point you can reach in thirty minutes','Then turn around. You will have seen somewhere new either way.','outdoors physical city screenfree','any','out',60,0],
['Watch the sun come up','Set the alarm tonight. Take a flask. Say nothing for the first ten minutes.','outdoors morning calm nature','any','out',75,0],
['Find water and follow it','A river, a canal, a stream. Downstream, until it gets boring.','outdoors nature physical','any','out',120,0],
['Learn five trees on your street','Enough to know them next winter with no leaves on.','learning nature outdoors quick','any','out',40,0],
['Swim outside','Lake, sea, lido. It is always colder in the mind than in the water.','water physical outdoors energetic','any','out',90,1],
['Go somewhere with no plan and no map','Get off two stops early and walk the rest by instinct.','outdoors city adventure screenfree','any','out',75,0],
['Climb the highest thing nearby','Hill, tower, multistorey. Look at where you live from above.','outdoors physical city','any','out',90,0],
['Take a night walk','Same route you know in daylight, different world after eleven.','outdoors night calm screenfree','any','out',45,0],
['Pick something and eat it','Blackberries, wild garlic, apples nobody is collecting. Check first, obviously.','nature food outdoors learning','any','out',60,0],
['Sit in one place outdoors for an hour','No book, no phone. Long enough that the birds forget about you.','calm nature screenfree outdoors','any','out',60,0],
['Plant something','A window box counts. So does a tree, if you have the room.','nature hands making calm','any','any',60,1],
['Cycle somewhere you would normally drive','Same errand, different half of the day.','physical outdoors energetic city','any','out',75,0],
['Find the oldest thing in your area','A church, a wall, a milestone, a tree. Go and stand next to it.','outdoors learning city nostalgic','any','out',75,0],
['Fly a kite badly','Cheap kite, open ground, wind. Absurd, and it works every time.','outdoors silly energetic screenfree','any','out',60,1],

// — physical —
['Run the loop you always mean to run','Slowly. Slower than that. The point is doing it, not doing it well.','physical energetic outdoors','any','out',40,0],
['Do the stretching you have been meaning to do','Twenty minutes on the floor with something on in the background.','physical calm quick','any','home',25,0],
['Try a class you would be bad at','Bouldering, pottery wheel, tango. One session. Be visibly a beginner.','physical learning social ambitious','any','out',90,2],
['Walk ten thousand steps in one go','Not accumulated. One walk, one podcast or none at all.','physical outdoors longhaul','any','out',120,0],
['Learn to do one pull-up','Or one more than you can now. Start tonight, in a doorway.','physical ambitious learning','any','home',20,1],
['Swim laps until you lose count','Goggles on, no watch, get out when you are done.','physical water calm','any','out',60,1],
['Skateboard, badly, in an empty car park','Sunday morning. Helmet. No audience.','physical silly energetic outdoors','any','out',60,1],
['Dance to three songs with the door shut','Full effort. Nobody is filming.','physical silly energetic quick','any','home',15,0],
['Walk somewhere and get the bus back','The commitment is one way, which is what makes it easy to start.','physical outdoors city','any','out',90,1],
['Throw something and catch it a thousand times','Juggling, a tennis ball off a wall. Stupidly meditative.','physical hands calm quick','any','any',30,0],

// — learning —
['Learn twenty words of a language you will never speak','Enough to read a menu and be polite. That is a real thing to have.','learning words quick','any','any',30,0],
['Read the Wikipedia article you keep meaning to read','Then read one it links to. Stop after three.','learning quick calm','any','any',30,0],
['Learn how the thing in your house actually works','The boiler, the fuse box, the lock. Then you own it instead of fearing it.','learning hands quick','any','home',40,0],
['Teach yourself one knot','A bowline. It takes ten minutes and you use it forever.','learning hands quick screenfree','any','any',15,0],
['Find out where your water comes from','Reservoir, river, aquifer. Then go and look at it.','learning outdoors nature','any','any',90,0],
['Learn to identify five birds by sound','Start with the loud ones. Then you can never unhear them.','learning nature outdoors calm','any','out',45,0],
['Read a whole issue of a magazine about something you know nothing about','Fishing, horology, poultry. The specialist press is a wonder.','learning words calm','any','any',60,1],
['Work out one thing about your own money','What the pension is in, what a bill actually covers. One thing.','learning planning quick','any','home',40,0],

// — food —
['Cook something you have never cooked','Pick a dish, shop for it properly, take the whole evening.','food making hands calm','any','home',120,1],
['Make bread from scratch','It is mostly waiting, and the waiting is the good bit.','food making hands longhaul','any','home',240,0],
['Eat at the place you always walk past','The one with three tables and no website.','food city social splurge','any','out',90,1],
['Cook from one ingredient you have never used','Buy it because you do not know what it is, then find out.','food learning making','any','home',90,1],
['Make a proper breakfast on a weekday','Set the table. Eat sitting down. Radio, not phone.','food calm morning kindness','any','home',45,0],
['Bake something and give it away','Half the pleasure is the handover.','food making kindness social','any','home',120,1],
['Learn to make one cocktail properly','Measure it. Taste it. Make it again better.','food learning hands night','any','home',40,1],
['Have a picnic in unglamorous weather','A flask and a bench beat a table indoors more often than you would think.','food outdoors calm screenfree','any','out',75,1],
['Shop at a market instead of a supermarket','Talk to whoever is selling. Buy what looks best rather than what is on the list.','food social city morning','any','out',75,1],
['Make the thing your family used to make','Ring someone and get the method wrong first.','food nostalgic kindness making','any','home',120,1],

// — social —
['Ring somebody instead of texting them','The one you keep meaning to. Twenty minutes, no agenda.','social talking kindness quick','any','any',25,0],
['Have people over for something small','Toast and soup is a dinner party if you say it is.','social talking food kindness','group','home',180,1],
['Organise the thing everyone says they want to do','Somebody has to pick a date. Be that person once.','social planning ambitious kindness','group','any',30,0],
['Play a board game with actual people','On a table, with the box, arguing about the rules.','social competitive silly talking','group','home',120,1],
['Go to a pub quiz and lose','Team of three, no phones, take it far too seriously.','social competitive silly night talking','group','out',150,1],
['Ask somebody to teach you what they are good at','People love being asked. You get a skill and they get an hour of being an expert.','social learning talking kindness','group','any',90,0],
['Have one long conversation with no phones on the table','Put them in a drawer. It changes the shape of the evening.','social talking screenfree calm','any','any',120,0],
['Walk with somebody instead of sitting with them','Side by side is where the harder conversations actually happen.','social talking outdoors physical','group','out',75,0],
['Cook for people who do not usually get cooked for','Parents, a neighbour, whoever is having a hard month.','social food kindness','group','home',150,1],
['Start the group chat that becomes a monthly thing','Same day every month. Low bar, kept forever.','social planning kindness quick','group','any',20,0],

// — two of you —
['Cook one dish together with no recipe between you','One of you shops, one of you leads. Swap next time.','romance food making talking','two','home',120,1],
['Go somewhere neither of you has been','Pick it on a map, not on a review site.','romance adventure outdoors talking','two','out',240,1],
['Take a train one stop past where you usually get off','Whole afternoon, no plan, come back when you are hungry.','romance adventure city outdoors','two','out',240,1],
['Do a jigsaw and talk while you do it','The hands-busy conversation is a different conversation.','romance calm talking screenfree','two','home',150,0],
['Read the same thing and argue about it','One short story each, out loud if you like.','romance words talking learning','two','home',90,0],
['Get dressed up for no occasion','Then go somewhere that does not deserve it.','romance silly night city splurge','two','out',180,2],
['Dance in the kitchen','One song is enough. Two is showing off.','romance silly music quick','two','home',10,0],
['Plan a trip you might not take','Properly — dates, trains, a place to stay. Half the pleasure is here.','romance planning talking ambitious','two','home',90,0],
['Interview each other about something you have never asked about','Childhood holidays. First jobs. What they were frightened of at nine.','romance talking nostalgic calm','two','any',60,0],
['Watch the film that one of you loves and the other has not seen','No talking through it. Argue after.','romance watching talking night','two','home',150,0],
['Go for breakfast somewhere before work','It makes a Tuesday feel stolen.','romance food morning city','two','out',75,1],
['Learn something together, badly','A dance step, a language app, a knot. The being-bad-together is the point.','romance learning silly talking','two','home',45,0],
['Walk home from somewhere instead of getting a taxi','Late, cold, arm in arm. The best conversations are on the way back.','romance outdoors night talking physical','two','out',60,0],
['Write down five things you want to do this year and compare lists','Then pick the one that appears on both.','romance planning talking words','two','any',45,0],

// — kindness and community —
['Do the errand somebody else has been dreading','Ask first. Then just do it.','kindness social quick','any','any',45,0],
['Give away five things today','Not to a bin. To a person or a shop that will find one.','kindness quick calm','any','home',45,0],
['Turn up to a local meeting about something','Planning, the park, the library. Sit at the back and find out how it works.','kindness learning social city','any','out',90,0],
['Volunteer for one shift','Not forever. One shift, and see.','kindness social ambitious','any','out',180,0],
['Write to somebody who will never expect it','A teacher, an old boss, a writer. Say the specific thing they did.','kindness words nostalgic','any','any',30,0],
['Pick up litter on one street','Gloves, a bag, twenty minutes. Extremely satisfying, faintly smug.','kindness outdoors physical quick','any','out',30,0],
['Leave something good for a stranger to find','A book on a bench with a note in it.','kindness silly creative quick','any','out',25,0],

// — reset and rest —
['Do nothing for twenty minutes on purpose','Not a nap, not a screen. A chair and a window.','calm screenfree quick','any','home',20,0],
['Clear one surface completely','One. Then stop and look at it.','calm hands quick planning','any','home',30,0],
['Have a bath with the phone in another room','Actually another room. Not the shelf.','calm screenfree quick night','any','home',45,0],
['Go to bed absurdly early','Nine o clock. The next day is the point.','calm night quick','any','home',30,0],
['Delete an app for a week','Pick the one you would miss. That is the one.','calm screenfree planning quick','any','any',10,0],
['Put your affairs in order for one hour','Bills, appointments, the drawer of paper. Finite and enormously relieving.','planning calm quick','any','home',60,0],
['Walk with no destination and no podcast','Boredom is where the ideas come from. Give it a chance.','calm outdoors screenfree physical','any','out',45,0],

// — culture and watching —
['Watch a film by somebody whose name you do not know','Pick by country or year rather than by recommendation.','watching learning night calm','any','home',120,1],
['Go to a gallery for one room only','One room, forty minutes. Better than four floors in an hour.','watching learning city calm','any','out',60,1],
['Read a play out loud','Even alone. Especially alone.','words silly learning night','any','home',90,0],
['See a matinee on your own','Cinema, theatre, anything. Sitting on your own in the dark is underrated.','watching calm city solo','solo','out',150,2],
['Find the local history of your street','Archives, old maps, the library. Somebody has already done the work.','learning nostalgic city words','any','any',90,0],
['Watch something in a language you do not speak','Subtitles on. It sounds like the place it is from.','watching learning night calm','any','home',110,0],
['Go to a lecture or a talk about anything','Universities and museums put them on for free constantly.','learning social city talking','any','out',120,0],
['Reread the book that mattered when you were seventeen','It will have changed. So have you.','words nostalgic calm','any','home',180,0],

// — adventure and city —
['Take the first bus that arrives and ride it to the end','Then work out how to get home.','adventure city outdoors silly','any','out',180,1],
['Go somewhere by train with no bag','Out in the morning, back at night. No packing, no hotel.','adventure longhaul city outdoors splurge','any','out',480,2],
['Find the place in your town that tourists go to and go there','You have never been. Be embarrassed about it for ten minutes, then enjoy it.','adventure city learning','any','out',120,1],
['Sleep outside','Garden, balcony, hill. One night, and it resets something.','adventure outdoors nature night','any','out',600,1],
['Swap a day with somebody else','Do their hobby for an afternoon and make them do yours.','adventure social learning talking','group','any',180,1],
['Go out with a disposable camera and finish it','Twenty-seven frames, no deleting, a week to wait.','adventure creative city screenfree','any','out',120,1],
['Walk a whole road end to end','Pick a long one. It is a cross-section of where you live.','adventure outdoors physical city longhaul','any','out',180,0],
['Get up at five and go somewhere','Anywhere. The first two hours of a day are a different country.','adventure morning outdoors energetic','any','out',180,0]
];

/* A twist never changes the title, only what you are asked to do with it —
   `ok` decides which seeds it can ride on, and `tags` are added to the
   card's feature vector, so a twist is something taste can have a view about. */
const TWISTS = [
  {t:'Leave the phone at home for it.', ok:s=>s.where!=='home', tags:['screenfree']},
  {t:'Do it before nine in the morning.', ok:s=>s.min<=180, tags:['morning']},
  {t:'Do it after dark.', ok:s=>s.min<=180 && !s.tags.includes('morning'), tags:['night']},
  {t:'Only use what is already in the house.', ok:s=>s.tags.includes('making')||s.tags.includes('food'), tags:['cheap','making']},
  {t:'Bring somebody who would not choose it.', ok:s=>s.who==='any', tags:['social','talking']},
  {t:'Give the result away.', ok:s=>s.tags.includes('making')||s.tags.includes('food')||s.tags.includes('creative'), tags:['kindness']},
  {t:'Do it somewhere you have never done it.', ok:s=>s.min<=180, tags:['adventure']},
  {t:'Finish it in one sitting, however rough.', ok:s=>s.tags.includes('creative')||s.tags.includes('words'), tags:['ambitious']},
  {t:'Take a photograph of it when it is done.', ok:s=>true, tags:['creative']},
  {t:'Do it in silence.', ok:s=>s.min<=120, tags:['calm','screenfree']},
  {t:'Do it twice as slowly as you want to.', ok:s=>s.min<=120, tags:['calm']},
  {t:'Tell one person you are going to, before you start.', ok:s=>s.tags.includes('ambitious')||s.min>=90, tags:['social','planning']},
  {t:'Make it a fortnightly thing rather than a one-off.', ok:s=>s.min<=120, tags:['planning']},
  {t:'Do the worst possible version on purpose.', ok:s=>s.tags.includes('creative')||s.tags.includes('silly'), tags:['silly']},
  {t:'Write down one sentence about it afterwards.', ok:s=>true, tags:['words']}
];

/* The three questions the deck asks before it deals. `any` never filters. */
const WHO  = [['any','Anyone'],['solo','Just me'],['two','The two of us'],['group','A few of us']];
const WHERE= [['any','Anywhere'],['home','At home'],['out','Out']];
const TIME = [[0,'Any length'],[30,'Half an hour'],[90,'An evening'],[300,'An afternoon'],[600,'A whole day']];

/* Seeds carry derived tags so the model can learn about length and cost
   without being told about the numbers. */
const SEEDS = RAW.map(([t,d,tg,who,where,min,cost], i) => {
  const tags = tg.split(' ');
  if (cost === 0) tags.push('cheap'); if (cost === 2) tags.push('splurge');
  if (min <= 30) tags.push('quick'); if (min >= 240) tags.push('longhaul');
  if (who === 'solo') tags.push('solo'); if (who === 'two') tags.push('romance');
  if (where === 'out' && !tags.includes('outdoors')) tags.push('outdoors');
  return { id:'s'+i, t, d, tags:[...new Set(tags)], who, where, min, cost, src:'seed' };
});

export { TAGS, SEEDS, TWISTS, WHO, WHERE, TIME };
